### ISSUE TITLE
Negative durability causes crashes with Grind Enchantments

### ISSUE THREAD

**Issue by IMB11** [sylenthuntress/Unbreakable#5]
Grind Enchantments takes into account durability by the looks of it, and in some cases causes a crash due to the negative durability value.

**Comment by IMB11** [comment]
I will post logs shortly

**Comment by IMB11** [comment]
```log
java.lang.IllegalArgumentException:
    at sylenthuntress.unbreakable.event.DisplayShatterTooltip.getTooltip(DisplayShatterTooltip.java:31)
    at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35)
    at net.minecraft.client.gui.hud.InGameHud.renderHotbarItem(InGameHud.java:645)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:865)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:699)
    at net.minecraft.client.main.Main.main(Main.java:239)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

https://github.com/sylenthuntress/Unbreakable/blob/master/src/client/java/sylenthuntress/unbreakable/event/DisplayShatterTooltip.java#L31

**Comment by sylenthuntress** [comment]
I can't reproduce, nor do I know what could possibly be causing that exception, but I optimized the code (since it was one of the first bits of code I wrote x3) in hopes that it might fix the issue in some way. More information (e.g the items that crashed, the enchantments that were removed, client-side mods) would be helpful in fixing this.
